# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.TextField(default=datetime.datetime(2016, 3, 19, 6, 48, 40, 361662, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
