# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
