# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='text',
        ),
    ]
